// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/satriowisnugroho/book-store/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderItemRepositoryInterface is an autogenerated mock type for the OrderItemRepositoryInterface type
type OrderItemRepositoryInterface struct {
	mock.Mock
}

// CreateOrderItem provides a mock function with given fields: ctx, orderItem
func (_m *OrderItemRepositoryInterface) CreateOrderItem(ctx context.Context, orderItem *entity.OrderItem) error {
	ret := _m.Called(ctx, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OrderItem) error); ok {
		r0 = rf(ctx, orderItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderItemsByOrderID provides a mock function with given fields: ctx, orderID
func (_m *OrderItemRepositoryInterface) GetOrderItemsByOrderID(ctx context.Context, orderID int) ([]*entity.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderItemsByOrderID")
	}

	var r0 []*entity.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entity.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entity.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderItemRepositoryInterface creates a new instance of OrderItemRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderItemRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderItemRepositoryInterface {
	mock := &OrderItemRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
