// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// PostgresTransactionRepositoryInterface is an autogenerated mock type for the PostgresTransactionRepositoryInterface type
type PostgresTransactionRepositoryInterface struct {
	mock.Mock
}

// CommitTransactionQuery provides a mock function with given fields: ctx, tx
func (_m *PostgresTransactionRepositoryInterface) CommitTransactionQuery(ctx context.Context, tx *sqlx.Tx) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransactionQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTransactionQuery provides a mock function with given fields: ctx, tx
func (_m *PostgresTransactionRepositoryInterface) RollbackTransactionQuery(ctx context.Context, tx *sqlx.Tx) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTransactionQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartTransactionQuery provides a mock function with given fields: ctx
func (_m *PostgresTransactionRepositoryInterface) StartTransactionQuery(ctx context.Context) (*sqlx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartTransactionQuery")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sqlx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sqlx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostgresTransactionRepositoryInterface creates a new instance of PostgresTransactionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresTransactionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresTransactionRepositoryInterface {
	mock := &PostgresTransactionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
