basePath: /v1
definitions:
  entity.Book:
    properties:
      created_at:
        type: string
      id:
        type: integer
      isbn:
        type: string
      price:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  entity.LoginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entity.Order:
    properties:
      book_id:
        type: integer
      created_at:
        type: string
      fee:
        type: integer
      id:
        type: integer
      price:
        type: integer
      quantity:
        type: integer
      total_price:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  entity.OrderPayload:
    properties:
      book_id:
        type: integer
      quantity:
        type: integer
    type: object
  entity.RegisterPayload:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    type: object
  entity.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  response.ErrorBody:
    properties:
      errors:
        items:
          $ref: '#/definitions/response.ErrorInfo'
        type: array
      meta: {}
    type: object
  response.ErrorInfo:
    properties:
      code:
        type: integer
      field:
        type: string
      message:
        type: string
    type: object
  response.MetaInfo:
    properties:
      http_status:
        type: integer
    type: object
  response.SuccessBody:
    properties:
      data: {}
      message:
        type: string
      meta: {}
    type: object
host: localhost:9999
info:
  contact: {}
  description: An API Documentation
  title: Book Store API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: An API to show list of books
      operationId: book list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.Book'
                  type: array
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Show Book List
      tags:
      - Book
  /orders:
    get:
      consumes:
      - application/json
      description: An API to show history of orders
      operationId: order list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.Order'
                  type: array
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      security:
      - BearerAuth: []
      summary: Show History Order
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: An API to create an order
      operationId: create order
      parameters:
      - description: payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.OrderPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Order'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      security:
      - BearerAuth: []
      summary: Create an Order
      tags:
      - Order
  /users/login:
    post:
      consumes:
      - application/json
      description: An API to login
      operationId: login
      parameters:
      - description: payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.LoginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.User'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Login
      tags:
      - User
  /users/register:
    post:
      consumes:
      - application/json
      description: An API to register
      operationId: create user
      parameters:
      - description: payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RegisterPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.User'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Register
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
